version: '3'
services:
  webpage:
    build: ./flask # dockerfile
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_app.py
    expose:
      - 5000 # db connection
      - 8010 # uwsgi
  nginx:
    build: ./nginx # dockerfile
    restart: always
    ports:
      - "8000:8000"
  